version: '3.8'

services:
  jobboard:
    build: .
    command: make run
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
       - JAEGER_AGENT_HOST=jaeger
       - JAEGER_AGENT_PORT=6831
       - JAEGER_SERVICE_NAME=jobboard-jaeger
       - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    networks:
      - jaeger-example
      - backend
    depends_on:
      - jaeger


  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "5775:5775/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "5778:5778"
      - "14268:14268"
      - "9411:9411"
      - "14250:14250"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - jaeger-example

  prometheus:
      container_name: prometheus
      image: prom/prometheus:v2.28.0
      ports:
          - "9090:9090"
      volumes:
          - "./src/jobboard/configurator/metrics/prometheus.yml:/etc/prometheus/prometheus.yml"
      networks:
          - backend

  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.9
    ports:
      - "3000:3000"
    depends_on:
      - jobboard
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - backend


networks:
  jaeger-example:
  backend: