"""empty message

Revision ID: 7794fd8602f8
Revises:
Create Date: 2022-10-17 12:25:45.290028

"""

# revision identifiers, used by Alembic.
revision = "7794fd8602f8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
