name: Type
on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
          architecture: x64
      - run: pip install pytype==2022.1.31
      - run: pytype --config=pytype.cfg src/*